/** Mary Cassatt, aged 44 at the end of 1888.
 * Qualitative portrait study; dimensions, costume and movement are game art direction.
 */
export default {
  id: 'cassatt',
  signature: [
    'wide plum portrait hat with an asymmetric blue-grey ribbon and feather',
    'broad mature cheeks, substantial nose and quietly weighted eyelids',
    'fuller high-collared figure beneath a curved, layered capelet',
  ],
  silhouette: 'Fuller, upright adult woman with rounded hips, a settled waist and a broad asymmetric hat above compact pinned hair.',
  look: {
    hat: 'portrait',
    hair: 'pinned',
    hairColor: '#705345',
    beard: 'none',
    beardColor: '#705345',
    skin: '#dfb594',
    eyeColor: '#485450',
    presentation: 'woman',
    coat: 'cape',
    build: 'average',
    accessory: 'capelet',
    sleeves: 'cuffed',
    neckwear: 'none',
    coatColor: '#65536d',
    shirtColor: '#ded3c1',
    pantsColor: '#46434f',
    trim: '#b798a6',
    hatColor: '#62445d',
    hatBandColor: '#a6b9c5',
    stature: 1.015,
    shoulderWidth: 1.01,
    waistWidth: 1.13,
    hipWidth: 1.18,
    torsoDepth: 1.12,
    belly: 0.27,
    chest: 0.4,
    legLength: 1.0,
    torsoLength: 1.05,
    legThickness: 1.07,
    neckWidth: 0.96,
    handScale: 0.98,
    headWidth: 1.07,
    headLength: 0.99,
    stoop: 0.015,
    // Legacy proportions remain coherent wherever a roster preview reads look directly.
    jawWidth: 1.0,
    noseLength: 1.06,
    noseWidth: 1.03,
    browWeight: 0.83,
    hairline: 0.13,
    ageLines: 0.49,
  },
  face: {
    jawWidth: 1.0,
    chinWidth: 0.98,
    cheekbone: 1.06,
    cheekFullness: 0.67,
    foreheadSlope: 0.3,
    noseLength: 1.06,
    noseWidth: 1.03,
    noseBridge: 1.03,
    noseTip: 0.98,
    eyeSpacing: 1.0,
    eyeSize: 0.92,
    eyeTilt: 0.015,
    eyeDepth: 0.43,
    browWeight: 0.83,
    lidWeight: 0.55,
    mouthWidth: 0.96,
    lipFullness: 0.94,
    earSize: 0.95,
    age: 0.49,
    asymmetry: -0.055,
    freckles: 0.025,
    beardLength: 1.0,
    beardDensity: 1.0,
    moustacheShape: 'none',
    hairPart: -0.26,
    hairWave: 0.48,
  },
  motion: {
    cadence: 1.04,
    stride: 0.96,
    hipSway: 0.86,
    shoulderSway: 0.84,
    forwardLean: 0.026,
    headSteadiness: 1.18,
    stanceWidth: 1.08,
    footLift: 0.95,
    idleBreath: 0.89,
    turnLag: 0.94,
    handEnergy: 0.85,
  },
  tailoring: {
    fabric: 'velvet',
    weave: 0.29,
    roughness: 0.89,
    wear: 0.16,
    foldScale: 1.16,
    buttonMetal: 'horn',
    seamContrast: 0.76,
  },
  references: [
    {
      title: 'Mary Cassatt, Portrait of the Artist — The Metropolitan Museum of Art',
      url: 'https://www.metmuseum.org/art/collection/search/10409',
      date: '1878',
      observed: 'The inspected self-portrait shows a softly rounded cheek and chin, a defined nose, swept-up dark hair under an ornamented hat, and a high light collar. It predates the setting by ten years; the Met describes the pose as asymmetrical.',
    },
    {
      title: 'Mary Cassatt Self-Portrait — National Portrait Gallery, Smithsonian Institution',
      url: 'https://npg.si.edu/object/npg_NPG.76.33',
      date: 'c. 1880',
      observed: 'The inspected museum reproduction shows full cheek planes, a clear elongated nose bridge, modest lips, dark defined eyes with visible lower-lid shadows, and hair gathered below a large hat. The object page rejected direct access; the Smithsonian curriculum and Art Institute reproduction supplied the accessible evidence.',
    },
    {
      title: 'Expanding Roles of Women — Smithsonian National Portrait Gallery, pp. 66–67',
      url: 'https://npg.si.edu/sites/default/files/npg_women-curriculum_guide_interactive-fields_final.pdf',
      date: 'c. 1880 portrait; museum teaching guide',
      observed: 'The opened guide identifies the self-portrait, medium and approximate date, and discusses its active return of the viewer’s gaze. This supports a steady, attentive gaze; it does not document a historical gait.',
    },
    {
      title: 'Cassatt’s Modern Vision of the Everyday — Art Institute of Chicago, museum-hosted portrait reproduction',
      url: 'https://artic-web.imgix.net/null28a55ead-0551-43f3-bdb7-cad3f126df0c/NPG-NPG_76_33Cassatt_d1.jpg?auto=format%2Ccompress&crop=faces%2Ccenter&fit=crop&h=2152&q=80&rect=0%2C0%2C2974%2C4000&w=1600',
      date: 'c. 1880',
      observed: 'Actual image inspected as the visual source for the National Portrait Gallery work. The painted hat is light, the clothing blue-green and the flesh shadows cool; the game’s plum palette and feather are an intentional redesign, not a colour transcription.',
    },
  ],
};
