/**
 * Paul Cézanne, age 49 at the end of 1888.
 * Portrait-informed sculpture; build, colours, wardrobe and movement are game art direction.
 */
export default {
  id: 'cezanne',
  signature: [
    'bare domed forehead above a broad, dense brown-grey beard',
    'substantial rounded waist and belly in a short wool waistcoat',
    'rolled pale sleeves, ochre waist apron and thick planted legs',
  ],
  silhouette: 'Stocky, deep-bodied adult with a broad waist, shorter legs and a quiet forward set.',
  look: {
    hat: 'none',
    hair: 'bald',
    hairColor: '#65594d',
    beard: 'full',
    beardColor: '#706252',
    beardShape: 'fan',
    skin: '#d2a681',
    eyeColor: '#615345',
    hairline: 0.9,
    ageLines: 0.64,
    build: 'broad',
    stature: 0.99,
    shoulderWidth: 1.18,
    waistWidth: 1.4,
    hipWidth: 1.18,
    torsoDepth: 1.3,
    belly: 0.74,
    chest: 0.3,
    legLength: 0.94,
    torsoLength: 1.1,
    legThickness: 1.23,
    neckWidth: 1.16,
    handScale: 1.07,
    headWidth: 1.12,
    headLength: 0.99,
    stoop: 0.05,
    // Keep legacy sculpture values aligned with the detailed face profile.
    jawWidth: 1.16,
    noseLength: 1.08,
    noseWidth: 1.21,
    browWeight: 1.23,
    coat: 'vest',
    coatColor: '#575348',
    shirtColor: '#cfc2a8',
    pantsColor: '#4f483c',
    trim: '#b9a466',
    sleeves: 'rolled',
    neckwear: 'none',
    accessory: 'waistapron',
    apronColor: '#aa9471',
  },
  face: {
    jawWidth: 1.16,
    chinWidth: 1.1,
    cheekbone: 1.12,
    cheekFullness: 0.65,
    foreheadSlope: 0.38,
    noseLength: 1.08,
    noseWidth: 1.21,
    noseBridge: 1.09,
    noseTip: 1.1,
    eyeSpacing: 0.98,
    eyeSize: 0.9,
    eyeTilt: -0.025,
    eyeDepth: 0.65,
    browWeight: 1.23,
    lidWeight: 0.64,
    mouthWidth: 1.06,
    lipFullness: 0.82,
    earSize: 1.1,
    age: 0.64,
    asymmetry: 0.08,
    freckles: 0.04,
    beardLength: 1.2,
    beardDensity: 1.25,
    moustacheShape: 'drooping',
    hairPart: 0,
    hairWave: 0.32,
  },
  motion: {
    cadence: 0.91,
    stride: 0.91,
    hipSway: 0.74,
    shoulderSway: 0.86,
    forwardLean: 0.025,
    headSteadiness: 1.2,
    stanceWidth: 1.18,
    footLift: 0.9,
    idleBreath: 1.08,
    turnLag: 1.17,
    handEnergy: 0.72,
  },
  tailoring: {
    fabric: 'wool',
    weave: 0.72,
    roughness: 0.89,
    wear: 0.34,
    foldScale: 0.93,
    buttonMetal: 'horn',
    seamContrast: 0.73,
  },
  references: [
    {
      title: 'Self Portrait — National Gallery, London, NG4135',
      url: 'https://www.nationalgallery.org.uk/paintings/paul-cezanne-self-portrait',
      date: 'about 1880–81',
      observed: 'The museum describes a domed cranium, a calm gaze and unequal eyes. These guide the exposed rounded forehead and restrained facial asymmetry; the portrait predates the setting by about eight years.',
    },
    {
      title: 'Self-Portrait [recto] — National Gallery of Art, 1985.64.85.a',
      url: 'https://www.nga.gov/artworks/66485-self-portrait-recto',
      date: 'c. 1880/1882',
      observed: 'The three-quarter graphite head and the museum page describe a bald forehead, broad nose, recessed eyes and full facial hair. Qualitative form reference, not measured anatomy; the page labels its visual description automatically generated.',
    },
    {
      title: 'Self-Portrait — The Phillips Collection, 0288',
      url: 'https://www.phillipscollection.org/collection/self-portrait',
      date: 'between 1878 and 1880',
      observed: 'The collection discusses a large balding head, uneven ruddy facial planes and facial hair that largely hides the mouth and neck. This informs broad cheeks, a dense beard and a low-contrast mouth; the earlier image is aged modestly for 1888.',
    },
  ],
};
