// Age 54 at the end of 1888. All dimensions are game modelling factors.
export default {
  id: 'degas',
  signature: [
    'exposed high crown with close gray side hair and a compact square beard',
    'long charcoal double-breasted coat with a narrow formal silhouette',
    'deep-set measured gaze, substantial nose and slightly advanced head',
  ],
  silhouette: 'A mature, moderate build held in a long, nearly straight formal coat; the bare high crown, compact beard and slight upper-back inclination remain readable without colour.',
  look: {
    hat: 'none',
    hair: 'bald',
    hairColor: '#756f65',
    beard: 'short',
    beardShape: 'square',
    beardColor: '#79736b',
    skin: '#d3af94',
    eyeColor: '#514e46',
    coat: 'doublebreast',
    coatColor: '#373b45',
    shirtColor: '#d7d3c4',
    pantsColor: '#303740',
    trim: '#a5abb5',
    hatColor: '#373b45',
    hatBandColor: '#303740',
    apronColor: '#a5abb5',
    build: 'average',
    sleeves: 'cuffed',
    neckwear: 'cravat',
    accessory: 'none',
    stature: 1.025,
    shoulderWidth: 1.02,
    waistWidth: 1.06,
    hipWidth: 0.98,
    torsoDepth: 1.06,
    belly: 0.18,
    chest: 0.21,
    legLength: 1.04,
    torsoLength: 1.02,
    legThickness: 0.95,
    neckWidth: 0.93,
    handScale: 1.0,
    headWidth: 0.97,
    headLength: 1.07,
    stoop: 0.06,
    hairline: 0.89,
    ageLines: 0.67,
    jawWidth: 1.07,
    noseLength: 1.20,
    noseWidth: 1.02,
    browWeight: 1.26,
  },
  face: {
    jawWidth: 1.07,
    chinWidth: 1.06,
    cheekbone: 1.09,
    cheekFullness: 0.38,
    foreheadSlope: 0.40,
    noseLength: 1.20,
    noseWidth: 1.02,
    noseBridge: 1.18,
    noseTip: 1.08,
    eyeSpacing: 0.98,
    eyeSize: 0.91,
    eyeTilt: -0.035,
    eyeDepth: 0.69,
    browWeight: 1.26,
    lidWeight: 0.66,
    mouthWidth: 0.94,
    lipFullness: 0.77,
    earSize: 1.05,
    age: 0.67,
    asymmetry: 0.045,
    freckles: 0.0,
    beardLength: 0.78,
    beardDensity: 0.93,
    moustacheShape: 'trimmed',
    hairPart: 0.0,
    hairWave: 0.08,
  },
  motion: {
    cadence: 0.92,
    stride: 0.97,
    hipSway: 0.72,
    shoulderSway: 0.69,
    forwardLean: 0.032,
    headSteadiness: 1.24,
    stanceWidth: 1.04,
    footLift: 0.89,
    idleBreath: 0.78,
    turnLag: 1.08,
    handEnergy: 0.69,
  },
  tailoring: {
    fabric: 'wool',
    weave: 0.62,
    roughness: 0.89,
    wear: 0.18,
    foldScale: 1.08,
    buttonMetal: 'horn',
    seamContrast: 0.72,
  },
  references: [
    {
      title: 'Apothéose de Degas — Musée d’Orsay, photographed by Walter Barnes, arranged by Degas',
      url: 'https://www.musee-orsay.fr/fr/oeuvres/apotheose-de-degas-141886',
      date: '1885',
      observed: 'Near-period group photograph: Degas at the centre has a high exposed forehead, a compact beard, strongly marked brows and dark formal clothing. The seated staging is not evidence of his habitual posture.',
    },
    {
      title: 'Self-Portrait in Library (Hand to Chin) — The Metropolitan Museum of Art',
      url: 'https://www.metmuseum.org/art/collection/search/296287',
      date: 'probably 1895',
      observed: 'Later photographic profile: receded temple hair, an extended nasal bridge with a rounded tip, a pronounced eye socket and substantial cheek plane. Used only to clarify structure; its later age and hand-obscured mouth are not copied literally into the 1888 character.',
    },
  ],
};
