// Paul Gauguin, age 40 at 31 December 1888.
// Portrait cues are qualitative; body factors and costume are game art direction.
export default {
  id: 'gauguin',
  signature: [
    'low asymmetric wine-red slouch beret over dark nape hair',
    'broad chest and square shoulders above a restrained waist',
    'long prominent nose, deep-set eyes and a dense drooping moustache',
  ],
  silhouette: 'A strong upper-body wedge: wide shoulders, substantial chest, long grounded legs and a low sideways beret.',
  look: {
    hat: 'slouchberet',
    hair: 'long',
    beard: 'moustache',
    build: 'broad',
    coat: 'doublebreast',
    sleeves: 'cuffed',
    neckwear: 'kerchief',
    accessory: 'none',
    skin: '#bd947c',
    hairColor: '#352c27',
    beardColor: '#302923',
    eyeColor: '#655b42',
    coatColor: '#805445',
    shirtColor: '#d2c5a6',
    pantsColor: '#3c4846',
    trim: '#ab8766',
    hatColor: '#703f42',
    hatBandColor: '#482f32',
    stature: 1.04,
    shoulderWidth: 1.31,
    waistWidth: 1.09,
    hipWidth: 1.07,
    torsoDepth: 1.22,
    belly: 0.20,
    chest: 0.66,
    legLength: 1.00,
    torsoLength: 1.05,
    legThickness: 1.17,
    neckWidth: 1.21,
    handScale: 1.10,
    headWidth: 1.07,
    headLength: 1.05,
    stoop: 0.012,
    hairline: 0.14,
    ageLines: 0.40,
  },
  face: {
    jawWidth: 1.18,
    chinWidth: 1.16,
    cheekbone: 1.18,
    cheekFullness: 0.38,
    foreheadSlope: 0.34,
    noseLength: 1.25,
    noseWidth: 1.17,
    noseBridge: 1.24,
    noseTip: 1.10,
    eyeSpacing: 0.98,
    eyeSize: 0.91,
    eyeTilt: -0.018,
    eyeDepth: 0.62,
    browWeight: 1.26,
    lidWeight: 0.58,
    mouthWidth: 1.10,
    lipFullness: 0.86,
    earSize: 1.07,
    age: 0.40,
    asymmetry: 0.06,
    freckles: 0.025,
    beardLength: 1.12,
    beardDensity: 1.22,
    moustacheShape: 'drooping',
    hairPart: -0.24,
    hairWave: 0.36,
  },
  motion: {
    cadence: 0.94,
    stride: 1.10,
    hipSway: 0.75,
    shoulderSway: 1.05,
    forwardLean: 0.029,
    headSteadiness: 1.22,
    stanceWidth: 1.18,
    footLift: 0.92,
    idleBreath: 1.04,
    turnLag: 1.10,
    handEnergy: 0.78,
  },
  tailoring: {
    fabric: 'wool',
    weave: 0.62,
    roughness: 0.88,
    wear: 0.28,
    foldScale: 1.12,
    buttonMetal: 'horn',
    seamContrast: 0.72,
  },
  references: [
    {
      title: 'Self-Portrait with Portrait of Emile Bernard (Les misérables) — Van Gogh Museum',
      url: 'https://catalogues.vangoghmuseum.com/contemporaries-of-van-gogh-1/cat57',
      date: '1888',
      observed: 'Near-period facial reference. Strong nose, dark hair and moustache inform the identity; the museum explains that the facial drawing and red colour were deliberately abstract and symbolic, so neither colour nor proportions are treated as literal measurements.',
    },
    {
      title: 'Self-Portrait Dedicated to Carrière — National Gallery of Art',
      url: 'https://www.nga.gov/artworks/66418-self-portrait-dedicated-carriere',
      date: '1888 or 1889',
      observed: 'The museum describes a broad nose bridge, under-eye hollows, an uneven brow, a prominent chin and dark hair brushed back at the temples. Those relationships inform the sculpted planes; painted green hair and eyes are not treated as natural colour evidence.',
    },
    {
      title: 'Self-Portrait — National Gallery of Art',
      url: 'https://www.nga.gov/artworks/46625-self-portrait',
      date: '1889 — one year after the setting',
      observed: 'The museum describes a prominent hooked nose, brushy moustache, arched brows and dark hair extending behind the head. Used as a later cross-check for the nose, moustache and hair silhouette, not an 1888 wardrobe record.',
    },
  ],
};
