/** Henri de Toulouse-Lautrec, age 24 at the end of 1888.
 * Museum portraits guide likeness; dimensions, costume colours and movement
 * are game art direction. Preserve an adult upper body above shorter legs.
 */
export default {
  id: 'lautrec',
  signature: [
    'compact dark bowler above broad brows and round glasses',
    'adult shoulders and long tailored torso above distinctly short legs',
    'smoky plum frock coat, pale collar and close square beard',
  ],
  silhouette: 'Adult head, hands and upper body; short trouser legs, a compact bowler crown and a composed upright carriage.',
  look: {
    hat: 'bowler',
    hair: 'curly',
    hairColor: '#332b28',
    beard: 'short',
    beardColor: '#3a2e2a',
    beardShape: 'square',
    skin: '#d8b395',
    eyeColor: '#4f4a3a',
    coat: 'frock',
    coatColor: '#52454e',
    shirtColor: '#e3d6bd',
    pantsColor: '#48454a',
    trim: '#bc9b6a',
    hatColor: '#322e32',
    hatBandColor: '#514346',
    sleeves: 'cuffed',
    neckwear: 'bow',
    accessory: 'glasses',
    build: 'broad',
    stature: 0.8444444444,
    shoulderWidth: 1.06,
    waistWidth: 1.06,
    hipWidth: 1.03,
    torsoDepth: 1.04,
    belly: 0.12,
    chest: 0.18,
    legLength: 0.65,
    torsoLength: 1.13,
    legThickness: 0.96,
    neckWidth: 1.04,
    handScale: 1.04,
    headWidth: 1.05,
    headLength: 1.03,
    stoop: 0.014,
    jawWidth: 1.05,
    noseLength: 1.22,
    noseWidth: 1.12,
    hairline: 0.1,
    ageLines: 0.1,
  },
  face: {
    jawWidth: 1.05,
    chinWidth: 0.94,
    cheekbone: 1.03,
    cheekFullness: 0.43,
    foreheadSlope: 0.21,
    noseLength: 1.22,
    noseWidth: 1.12,
    noseBridge: 1.21,
    noseTip: 1.1,
    eyeSpacing: 0.96,
    eyeSize: 0.93,
    eyeTilt: -0.035,
    eyeDepth: 0.46,
    browWeight: 1.24,
    lidWeight: 0.35,
    mouthWidth: 1.06,
    lipFullness: 1.13,
    earSize: 1.02,
    age: 0.08,
    asymmetry: 0.045,
    freckles: 0.025,
    beardLength: 0.88,
    beardDensity: 1.07,
    moustacheShape: 'trimmed',
    hairPart: -0.28,
    hairWave: 0.62,
  },
  motion: {
    cadence: 1.1,
    stride: 0.88,
    hipSway: 0.72,
    shoulderSway: 0.76,
    forwardLean: 0.026,
    headSteadiness: 1.22,
    stanceWidth: 1.08,
    footLift: 0.9,
    idleBreath: 0.87,
    turnLag: 0.9,
    handEnergy: 0.9,
  },
  tailoring: {
    fabric: 'wool',
    weave: 0.42,
    roughness: 0.83,
    wear: 0.18,
    foldScale: 0.78,
    buttonMetal: 'horn',
    seamContrast: 0.74,
  },
  references: [
    {
      title: 'Henri Rachou, Portrait du peintre Henri de Toulouse-Lautrec — Musée des Augustins, RO 1020',
      url: 'https://collections.augustins.toulouse.fr/fr/notice/ro-1020-portrait-du-peintre-henri-de-toulouse-lautrec-0b227dc2-9fe3-42c4-baa9-4398ff06a82b',
      date: '1883',
      observed: 'Visually inspected museum reproduction: strong dark brows, long nose, full lips and youthful cheek planes; dark tailored clothing and a small rounded hat. Five years before the setting.',
    },
    {
      title: 'Maurice Guibert, Toulouse-Lautrec en pied avec sa canne — Fondation Pierre Gianadda, exhibition press catalogue p.25',
      url: 'https://www.gianadda.ch/wp-content/uploads/2017/12/DP-TOULOUSE-LAUTREC-_-FONDATION-PIERRE-GIANADDA.pdf',
      date: 'c.1892',
      observed: 'The catalogue identifies this full-length photograph and credits Musée Toulouse-Lautrec, Albi. Later proportion reference, not a verified 1888 costume or movement record.',
    },
    {
      title: 'Le portrait dans l’art — GrandPalaisRmn, p.55',
      url: 'https://grandpalaisrmn.fr/sites/default/files/media/files/Livret_HDA_MicroFolies_Portraitdanslart.pdf',
      date: '2019 educational publication; includes the 1883 Rachou portrait',
      observed: 'Museum exhibition account gives a height of 1.52 m. Only that approximate overall stature is treated as biographical; the mesh ratios are modelling choices.',
    },
    {
      title: 'Conférences en ligne, Toulouse-Lautrec discussion — Musée des Augustins',
      url: 'https://augustins.toulouse.fr/conferences-en-ligne/',
      date: 'Museum interpretation of the 1883 portrait',
      observed: 'The museum discusses the young sitter’s smooth, full face, careful dress and shorter legs. The character advances the youthful portrait to age 24 without assigning a medical diagnosis.',
    },
  ],
};
