// Claude Monet, age 48 at the end of 1888. Body ratios and wardrobe are game art direction.
export default {
  id: 'monet',
  signature: [
    'broad olive garden brim above a dark fan beard',
    'rounded deep smock with a substantial waist and hips',
    'firm shaded brow and projecting nose above full cheeks',
  ],
  silhouette: 'Broad, rounded and grounded; a wide garden brim, deep smock belly and thick trouser legs form three readable masses.',
  look: {
    hat: 'garden',
    hair: 'short',
    beard: 'full',
    beardShape: 'fan',
    build: 'broad',
    skin: '#d0a080',
    hairColor: '#403d35',
    beardColor: '#473d30',
    eyeColor: '#4a4b3b',
    coat: 'smock',
    coatColor: '#617361',
    shirtColor: '#d2ceb6',
    pantsColor: '#40534d',
    trim: '#a9c2bc',
    hatColor: '#85835b',
    hatBandColor: '#59563d',
    sleeves: 'cuffed',
    neckwear: 'kerchief',
    accessory: 'none',
    stature: 1.01,
    shoulderWidth: 1.20,
    waistWidth: 1.40,
    hipWidth: 1.26,
    torsoDepth: 1.32,
    belly: 0.74,
    chest: 0.39,
    legLength: 0.97,
    torsoLength: 1.08,
    legThickness: 1.22,
    neckWidth: 1.18,
    handScale: 1.08,
    headWidth: 1.10,
    headLength: 1.02,
    stoop: 0.025,
    jawWidth: 1.17,
    noseLength: 1.20,
    noseWidth: 1.06,
    hairline: 0.39,
    ageLines: 0.52,
    browWeight: 1.19,
  },
  face: {
    jawWidth: 1.17,
    chinWidth: 1.08,
    cheekbone: 1.05,
    cheekFullness: 0.62,
    foreheadSlope: 0.40,
    noseLength: 1.20,
    noseWidth: 1.06,
    noseBridge: 1.21,
    noseTip: 1.10,
    eyeSpacing: 0.96,
    eyeSize: 0.92,
    eyeTilt: -0.025,
    eyeDepth: 0.58,
    browWeight: 1.19,
    lidWeight: 0.60,
    mouthWidth: 0.98,
    lipFullness: 0.86,
    earSize: 1.10,
    age: 0.52,
    asymmetry: 0.07,
    freckles: 0.02,
    beardLength: 1.16,
    beardDensity: 1.19,
    moustacheShape: 'drooping',
    hairPart: -0.40,
    hairWave: 0.45,
  },
  motion: {
    cadence: 0.90,
    stride: 0.97,
    hipSway: 0.80,
    shoulderSway: 0.79,
    forwardLean: 0.032,
    headSteadiness: 1.18,
    stanceWidth: 1.18,
    footLift: 0.88,
    idleBreath: 1.12,
    turnLag: 1.18,
    handEnergy: 0.78,
  },
  tailoring: {
    fabric: 'linen',
    weave: 0.78,
    roughness: 0.88,
    wear: 0.34,
    foldScale: 1.22,
    buttonMetal: 'horn',
    seamContrast: 0.82,
  },
  references: [
    {
      title: 'John Singer Sargent, Claude Monet — National Academy of Design',
      url: 'https://artsandculture.google.com/asset/claude-monet-john-singer-sargent/PgEv2gbWxFOD8A?hl=en',
      date: '1887 in the museum record; accompanying text allows an earlier 1885 date',
      observed: 'Museum-authored record and displayed portrait inspected: a firm brow, projecting nose, visible ear, swept dark hair with gray at the temple, and a dense dark beard. This near-period profile anchors the age-48 face; it does not establish body weight.',
    },
    {
      title: 'Auguste Renoir, Claude Monet — Musée d’Orsay',
      url: 'https://www.musee-orsay.fr/en/artworks/claude-monet-496',
      date: '1875, thirteen years before the game setting',
      observed: 'Record and portrait inspected: dark full beard and moustache, shadowed eyes beneath a firm brow, and a prominent nose; dark painting clothes and a small round hat. The game’s olive wide-brim garden hat and substantial rounded build are invented choices, not observations from this portrait.',
    },
  ],
};
