// Morisot at the end of 1888, aged 47. Ratios and movement are game art direction.
export default {
  id: 'morisot',
  signature: [
    'compact ribbon bonnet over silver-gray center-part waves',
    'long oval mature face with a tapered chin and attentive green eyes',
    'light narrow-shouldered figure in a high collar and close-draped shawl',
  ],
  silhouette: 'Light, upright adult build; narrow shoulders, a softly shaped waist, and a long high-collared coat beneath a compact bonnet.',
  look: {
    presentation: 'woman',
    build: 'slim',
    hat: 'bonnet',
    hair: 'waved',
    beard: 'none',
    coat: 'highcollar',
    sleeves: 'cuffed',
    neckwear: 'none',
    accessory: 'shawl',
    skin: '#d9b49f',
    hairColor: '#aaa6a0',
    beardColor: '#aaa6a0',
    eyeColor: '#59684f',
    coatColor: '#536579',
    shirtColor: '#d4cfc0',
    pantsColor: '#444c5b',
    trim: '#a2acb1',
    hatColor: '#3e434c',
    hatBandColor: '#aaa3af',
    stature: 0.975,
    shoulderWidth: 0.84,
    waistWidth: 0.89,
    hipWidth: 1.02,
    torsoDepth: 0.88,
    belly: 0.09,
    chest: 0.32,
    legLength: 1.03,
    torsoLength: 0.99,
    legThickness: 0.87,
    neckWidth: 0.83,
    handScale: 0.94,
    headWidth: 0.89,
    headLength: 1.10,
    stoop: 0.017,
    // Keep legacy readers consistent with the full sculpture profile below.
    jawWidth: 0.83,
    noseLength: 1.10,
    noseWidth: 0.84,
    browWeight: 0.84,
    hairline: 0.12,
    ageLines: 0.57,
  },
  face: {
    jawWidth: 0.83,
    chinWidth: 0.82,
    cheekbone: 1.04,
    cheekFullness: 0.43,
    foreheadSlope: 0.33,
    noseLength: 1.10,
    noseWidth: 0.84,
    noseBridge: 1.04,
    noseTip: 0.94,
    eyeSpacing: 0.99,
    eyeSize: 0.96,
    eyeTilt: -0.015,
    eyeDepth: 0.44,
    browWeight: 0.84,
    lidWeight: 0.62,
    mouthWidth: 0.96,
    lipFullness: 0.92,
    earSize: 0.97,
    age: 0.57,
    asymmetry: 0.06,
    freckles: 0.02,
    // Neutral beard geometry is inert when look.beard is 'none'.
    beardLength: 1.00,
    beardDensity: 1.00,
    moustacheShape: 'none',
    hairPart: 0.08,
    hairWave: 0.76,
  },
  motion: {
    cadence: 1.03,
    stride: 0.95,
    hipSway: 0.87,
    shoulderSway: 0.76,
    forwardLean: 0.023,
    headSteadiness: 1.20,
    stanceWidth: 0.92,
    footLift: 0.94,
    idleBreath: 0.79,
    turnLag: 0.94,
    handEnergy: 0.74,
  },
  tailoring: {
    fabric: 'wool',
    weave: 0.66,
    roughness: 0.90,
    wear: 0.19,
    foldScale: 0.80,
    buttonMetal: 'horn',
    seamContrast: 0.70,
  },
  references: [
    {
      title: 'Berthe Morisot, Autoportrait, 1885 — Musée Marmottan Monet',
      url: 'https://www.marmottan.fr/collections/berthe-morisot/',
      date: '1885',
      observed: 'The collection identifies the near-period self-portrait; its reproduction supplies the mature face and gray swept-hair direction.',
    },
    {
      title: 'Berthe Morisot et l’art du XVIIIe siècle — museum dossier, p.18',
      url: 'https://www.marmottan.fr/wp-content/uploads/2023/04/B18-DP_BAT-pages.pdf#page=18',
      date: '1885 artwork; 2023 dossier',
      observed: 'Visually inspected: center-part gray waves, a long oval face tapering at the chin, defined lids, restrained lips, and a dark high neck. Her painted garment is ochre; the blue wool costume and bonnet are invented.',
    },
    {
      title: 'Édouard Manet, Berthe Morisot au bouquet de violettes — Musée d’Orsay',
      url: 'https://www.musee-orsay.fr/en/artworks/berthe-morisot-au-bouquet-de-violettes-100102',
      date: '1872; sixteen years before the setting',
      observed: 'Earlier comparison for the tapered lower face, narrow nose and dark high neckline. The museum says her eyes were green despite Manet painting them black; the exact iris tone remains an approximation.',
    },
  ],
};
