// Camille Pissarro, age 58 at 31 December 1888.
// Portraits guide likeness; proportions, wardrobe and gait are game art direction.
export default {
  id: 'pissarro',
  signature: [
    'low drooping taupe cloth hat above a long gray-white beard',
    'deep-set eyes behind glasses, high forehead and a substantial brow',
    'soft bark-brown smock over a modest waist and gently inclined shoulders',
  ],
  silhouette: 'A gently inclined, softly rounded figure with a low floppy crown, long tapered beard and loose cuffed smock over ordinary-length legs.',
  look: {
    hat: 'floppy',
    hair: 'bald',
    beard: 'full',
    beardShape: 'flowing',
    build: 'slim',
    coat: 'smock',
    sleeves: 'cuffed',
    neckwear: 'kerchief',
    accessory: 'glasses',
    skin: '#cba58b',
    hairColor: '#aaa99d',
    beardColor: '#dad8cb',
    eyeColor: '#47473e',
    coatColor: '#655e4b',
    shirtColor: '#c0c3af',
    pantsColor: '#505b5d',
    trim: '#94b6bd',
    hatColor: '#a29c87',
    hatBandColor: '#756f60',
    stature: 0.985,
    shoulderWidth: 0.97,
    waistWidth: 1.07,
    hipWidth: 1.03,
    torsoDepth: 1.04,
    belly: 0.22,
    chest: 0.20,
    legLength: 0.98,
    torsoLength: 1.04,
    legThickness: 0.98,
    neckWidth: 0.94,
    handScale: 1.02,
    headWidth: 0.98,
    headLength: 1.08,
    stoop: 0.075,
    hairline: 0.92,
    ageLines: 0.72,
  },
  face: {
    jawWidth: 0.98,
    chinWidth: 0.91,
    cheekbone: 1.07,
    cheekFullness: 0.38,
    foreheadSlope: 0.44,
    noseLength: 1.21,
    noseWidth: 1.03,
    noseBridge: 1.17,
    noseTip: 1.06,
    eyeSpacing: 0.97,
    eyeSize: 0.91,
    eyeTilt: -0.024,
    eyeDepth: 0.68,
    browWeight: 1.18,
    lidWeight: 0.72,
    mouthWidth: 0.99,
    lipFullness: 0.77,
    earSize: 1.10,
    age: 0.72,
    asymmetry: 0.045,
    freckles: 0.04,
    beardLength: 1.31,
    beardDensity: 1.18,
    moustacheShape: 'drooping',
    hairPart: 0.08,
    hairWave: 0.30,
  },
  motion: {
    cadence: 0.94,
    stride: 0.96,
    hipSway: 0.78,
    shoulderSway: 0.83,
    forwardLean: 0.026,
    headSteadiness: 1.20,
    stanceWidth: 1.08,
    footLift: 0.92,
    idleBreath: 0.88,
    turnLag: 1.13,
    handEnergy: 0.77,
  },
  tailoring: {
    fabric: 'linen',
    weave: 0.72,
    roughness: 0.91,
    wear: 0.34,
    foldScale: 1.17,
    buttonMetal: 'horn',
    seamContrast: 0.65,
  },
  references: [
    {
      title: 'Self-Portrait (Camille Pissarro, par lui-meme) — National Gallery of Art',
      url: 'https://www.nga.gov/artworks/42668-self-portrait-camille-pissarro-par-lui-meme',
      date: 'c. 1890 — approximately two years after the setting',
      observed: 'The museum describes a long pale beard, moustache-covered mouth, deep-set eyes looking above low glasses, and a floppy light hat. These guide the beard, eyes and head silhouette; the monochrome print does not establish natural colouring or exact 1888 appearance.',
    },
    {
      title: "Portrait de l'artiste — Musée d'Orsay",
      url: 'https://www.musee-orsay.fr/fr/oeuvres/portrait-de-lartiste-366',
      date: '1873 — fifteen years before the setting',
      observed: 'The opened portrait image shows an exposed high forehead, strong brow, long nose and a flowing beard with a darker moustache. It informs forehead and nose relationships beneath the later hat; its earlier age, painted colour and beard tone are not copied as an 1888 record.',
    },
  ],
};
