// Renoir at 47 in the game's 1888 setting. Shape ratios and motion are art direction.
export default {
  id: 'renoir',
  signature: [
    'bare receding crown with a small sweep of reddish-brown hair',
    'narrow shoulders and waist in a short warm-brown waistcoat',
    'slender nose, light brows and a compact tapering reddish beard',
  ],
  silhouette: 'Lean, shallow-chested adult with narrow shoulders, a short fitted waistcoat, exposed rolled-sleeve forearms and a slight forward inclination.',
  look: {
    hat: 'none',
    hair: 'short',
    hairColor: '#79533d',
    beard: 'short',
    beardShape: 'pointed',
    beardColor: '#89593f',
    skin: '#deb79d',
    eyeColor: '#526166',
    coat: 'vest',
    coatColor: '#77554f',
    shirtColor: '#d8c6ab',
    pantsColor: '#505057',
    trim: '#8fa9b9',
    build: 'slim',
    accessory: 'none',
    sleeves: 'rolled',
    neckwear: 'bow',
    stature: 0.97,
    shoulderWidth: 0.83,
    waistWidth: 0.78,
    hipWidth: 0.86,
    torsoDepth: 0.83,
    belly: 0.035,
    chest: 0.14,
    legLength: 1.055,
    torsoLength: 0.97,
    legThickness: 0.79,
    neckWidth: 0.81,
    handScale: 0.90,
    headWidth: 0.90,
    headLength: 1.055,
    stoop: 0.022,
    hairline: 0.71,
    ageLines: 0.52,
    // Keep legacy face consumers consistent with the full sculpture below.
    jawWidth: 0.81,
    noseLength: 1.09,
    noseWidth: 0.80,
    browWeight: 0.78,
  },
  face: {
    jawWidth: 0.81,
    chinWidth: 0.80,
    cheekbone: 0.99,
    cheekFullness: 0.24,
    foreheadSlope: 0.22,
    noseLength: 1.09,
    noseWidth: 0.80,
    noseBridge: 1.08,
    noseTip: 0.95,
    eyeSpacing: 1.03,
    eyeSize: 0.90,
    eyeTilt: -0.017,
    eyeDepth: 0.42,
    browWeight: 0.78,
    lidWeight: 0.48,
    mouthWidth: 0.93,
    lipFullness: 0.83,
    earSize: 1.06,
    age: 0.52,
    asymmetry: 0.055,
    freckles: 0.025,
    beardLength: 0.93,
    beardDensity: 0.87,
    moustacheShape: 'drooping',
    hairPart: -0.36,
    hairWave: 0.28,
  },
  motion: {
    cadence: 1.09,
    stride: 0.96,
    hipSway: 0.79,
    shoulderSway: 0.83,
    forwardLean: 0.026,
    headSteadiness: 1.15,
    stanceWidth: 0.92,
    footLift: 0.94,
    idleBreath: 0.88,
    turnLag: 0.87,
    handEnergy: 0.96,
  },
  tailoring: {
    fabric: 'wool',
    weave: 0.42,
    roughness: 0.86,
    wear: 0.26,
    foldScale: 0.82,
    buttonMetal: 'horn',
    seamContrast: 0.72,
  },
  references: [
    {
      title: "Auguste Renoir, Portrait de l'artiste — Musée d'Orsay",
      url: 'https://www.musee-orsay.fr/fr/oeuvres/portrait-de-lartiste-487',
      date: '1879',
      observed: 'The enlarged museum reproduction shows an exposed high forehead between short parted brown hair, lightly indicated brows over small eyes, a narrow nose and a reddish-brown beard tapering under the chin. This is nine years before the setting; the stronger recession and middle-aged eyelids are the game interpretation.',
    },
    {
      title: "Frédéric Bazille, Pierre Auguste Renoir — Musée d'Orsay",
      url: 'https://www.musee-orsay.fr/en/artworks/pierre-auguste-renoir-63',
      date: '1867',
      observed: 'The enlarged seated three-quarter portrait gives a clear narrow projecting nose, a slim cheek-to-jaw transition, a visible ear and close reddish facial hair. The younger sitter wears a dark tailored coat and a pale collar. It informs facial continuity, not an exact 1888 build or wardrobe.',
    },
  ],
};
