/** Georges Seurat, age 29 at 31 December 1888.
 * Portrait observations and invented build/costume choices are separated in
 * docs/characters/seurat.md. All dimensions below are game modelling factors.
 */
export default {
  id: 'seurat',
  signature: [
    'bare swept-haired head with a long nose and tapered dark beard',
    'tall narrow frame carried upright over long legs',
    'close charcoal-teal frock coat with a pale stock at the throat',
  ],
  silhouette: 'Tall and spare, with a long-legged vertical line, narrow coat shoulders, and a compact bearded head held quietly above the stock collar.',
  look: {
    hat: 'none',
    hair: 'short',
    hairColor: '#302923',
    beard: 'full',
    beardColor: '#352b25',
    beardShape: 'pointed',
    hairline: 0.06,
    skin: '#d8b291',
    eyeColor: '#4a4034',
    ageLines: 0.12,
    coat: 'frock',
    coatColor: '#38494a',
    shirtColor: '#e5dcc5',
    pantsColor: '#353f3f',
    trim: '#cbbd92',
    hatColor: '#38494a',
    hatBandColor: '#cbbd92',
    apronColor: '#afa185',
    sleeves: 'cuffed',
    neckwear: 'stock',
    accessory: 'none',
    build: 'slim',
    // Preserve the existing physical-proxy invariant exactly.
    stature: 1.08,
    shoulderWidth: 0.89,
    waistWidth: 0.83,
    hipWidth: 0.88,
    torsoDepth: 0.86,
    belly: 0.04,
    chest: 0.18,
    legLength: 1.12,
    torsoLength: 0.98,
    legThickness: 0.85,
    neckWidth: 0.87,
    handScale: 0.97,
    headWidth: 0.92,
    headLength: 1.07,
    stoop: 0.008,
    jawWidth: 0.91,
    noseLength: 1.19,
    noseWidth: 0.93,
    browWeight: 1.08,
  },
  face: {
    jawWidth: 0.91,
    chinWidth: 0.89,
    cheekbone: 1.06,
    cheekFullness: 0.25,
    foreheadSlope: 0.24,
    noseLength: 1.19,
    noseWidth: 0.93,
    noseBridge: 1.16,
    noseTip: 0.99,
    eyeSpacing: 0.98,
    eyeSize: 0.95,
    eyeTilt: 0.012,
    eyeDepth: 0.52,
    browWeight: 1.08,
    lidWeight: 0.47,
    mouthWidth: 0.93,
    lipFullness: 0.88,
    earSize: 1.06,
    age: 0.16,
    asymmetry: -0.025,
    freckles: 0.015,
    beardLength: 1.03,
    beardDensity: 1.10,
    moustacheShape: 'trimmed',
    hairPart: -0.38,
    hairWave: 0.28,
  },
  motion: {
    cadence: 0.92,
    stride: 1.08,
    hipSway: 0.73,
    shoulderSway: 0.69,
    forwardLean: 0.012,
    headSteadiness: 1.23,
    stanceWidth: 0.91,
    footLift: 0.86,
    idleBreath: 0.78,
    turnLag: 0.84,
    handEnergy: 0.70,
  },
  tailoring: {
    fabric: 'wool',
    weave: 0.38,
    roughness: 0.82,
    wear: 0.16,
    foldScale: 0.74,
    buttonMetal: 'horn',
    seamContrast: 0.67,
  },
  references: [
    {
      title: 'Ernest Laurent, Portrait de Georges Seurat — Louvre, RF 23518',
      url: 'https://collections.louvre.fr/ark:/53355/cl020229715',
      date: '1883',
      observed: 'Three-quarter young face: long projecting nose, dark upper eye sockets, broad exposed forehead under swept hair, and a dense beard tapering below the chin. Monochrome drawing; colours and exact dimensions are not established.',
    },
    {
      title: 'National Gallery of Art, Picturing France 1830–1900, p.100',
      url: 'https://www.nga.gov/content/dam/ngaweb/Education/learning-resources/teaching-packets/pdfs/picturing_france.pdf#page=104',
      date: '1883 portrait, reproduced in museum teaching publication',
      observed: 'Reproduces and identifies the same Ernest Laurent portrait. This is corroborating publication of one likeness, not a second independent portrait or evidence for Seurat’s gait.',
    },
  ],
};
