// Paul Signac at 25: qualitative portrait cues, fictional naval wardrobe/build.
export default {
  id: 'signac',
  signature: [
    'flat pale sailor cap above a dark compact full beard',
    'broad square naval collar and cuffed blue wool blouse',
    'solid shoulders tapering to an unencumbered waist and planted legs',
  ],
  silhouette: 'A youthful, solid upper body with open shoulders, a modest waist taper, and a low horizontal sailor-cap crown.',
  look: {
    presentation: 'man',
    hat: 'sailor',
    hair: 'short',
    beard: 'full',
    beardShape: 'square',
    glasses: false,
    skin: '#dfb28f',
    hairColor: '#513d32',
    beardColor: '#614334',
    eyeColor: '#59635a',
    coat: 'sailor',
    build: 'broad',
    accessory: 'none',
    sleeves: 'cuffed',
    neckwear: 'kerchief',
    coatColor: '#304d58',
    shirtColor: '#ded8bd',
    pantsColor: '#35444b',
    trim: '#bfba94',
    hatColor: '#d5cfb5',
    hatBandColor: '#263a43',
    apronColor: '#b9ad8b',
    stature: 1.03,
    shoulderWidth: 1.17,
    waistWidth: 1.04,
    hipWidth: 1.02,
    torsoDepth: 1.08,
    belly: 0.16,
    chest: 0.42,
    legLength: 1.03,
    torsoLength: 1.03,
    legThickness: 1.08,
    neckWidth: 1.04,
    handScale: 1.04,
    headWidth: 1.04,
    headLength: 0.98,
    stoop: 0.004,
    hairline: 0.05,
    ageLines: 0.06,
    jawWidth: 1.04,
    noseLength: 1.13,
    noseWidth: 0.98,
    browWeight: 1.06,
  },
  face: {
    jawWidth: 1.04,
    chinWidth: 0.94,
    cheekbone: 1.13,
    cheekFullness: 0.47,
    foreheadSlope: 0.23,
    noseLength: 1.13,
    noseWidth: 0.98,
    noseBridge: 1.12,
    noseTip: 0.98,
    eyeSpacing: 1.01,
    eyeSize: 0.95,
    eyeTilt: 0.025,
    eyeDepth: 0.34,
    browWeight: 1.06,
    lidWeight: 0.27,
    mouthWidth: 1.03,
    lipFullness: 0.87,
    earSize: 1.06,
    age: 0.10,
    asymmetry: 0.055,
    freckles: 0.04,
    beardLength: 1.14,
    beardDensity: 1.17,
    moustacheShape: 'trimmed',
    hairPart: -0.23,
    hairWave: 0.24,
  },
  motion: {
    cadence: 1.06,
    stride: 1.03,
    hipSway: 0.94,
    shoulderSway: 1.10,
    forwardLean: 0.025,
    headSteadiness: 1.10,
    stanceWidth: 1.10,
    footLift: 1.02,
    idleBreath: 1.04,
    turnLag: 0.91,
    handEnergy: 1.02,
  },
  tailoring: {
    fabric: 'wool',
    weave: 0.58,
    roughness: 0.87,
    wear: 0.22,
    foldScale: 0.92,
    buttonMetal: 'horn',
    seamContrast: 0.76,
  },
  references: [
    {
      title: 'Camille Pissarro, Paul Signac (Portrait de Paul Signac) — National Gallery of Art',
      url: 'https://www.nga.gov/artworks/10105-paul-signac-portrait-de-paul-signac',
      date: 'c. 1890; approximately two years after the game setting',
      observed: 'Visually inspected museum zoom: straight prominent nose, pronounced cheekbone planes, short parted hair and a substantial compact beard. The etched shadows do not establish skin, hair or eye colour.',
    },
    {
      title: 'Musée d’Orsay, Signac collectionneur — educational brochure, p. 5',
      url: 'https://www.musee-orsay.fr/sites/default/files/2022-03/Brochure%20educative%20Orsay_0.pdf',
      date: '2021–2022 brochure; captions a portrait dated 1896',
      observed: 'The museum captions Théo van Rysselberghe’s 1896 Signac at the helm of his boat. This supports the maritime theme only; it is not evidence for the exact invented 1888 outfit.',
    },
  ],
};
