/** Vincent at 35 in the game's 1888 setting. Ratios are art direction, not measurements. */
export default {
  id: 'van-gogh',
  signature: [
    'frayed straw brim above a long copper-bearded face',
    'narrow blue linen smock with rolled sleeves and a pale apron',
    'lean long-legged stance with a slight forward inclination',
  ],
  silhouette: 'A wiry, tapered figure: broad straw brim, narrow shoulders and waist, clear forearms and long slim legs.',
  look: {
    hat: 'frayedstraw',
    hair: 'short',
    hairColor: '#886348',
    beard: 'short',
    beardColor: '#a6532e',
    beardShape: 'square',
    skin: '#d5a48c',
    eyeColor: '#68765b',
    coat: 'smock',
    coatColor: '#496773',
    shirtColor: '#ddd0b4',
    pantsColor: '#4b5148',
    trim: '#e7c764',
    hatColor: '#bea364',
    hatBandColor: '#78603b',
    apronColor: '#bca987',
    build: 'slim',
    accessory: 'apron',
    sleeves: 'rolled',
    neckwear: 'none',
    stature: 1,
    shoulderWidth: 0.88,
    waistWidth: 0.82,
    hipWidth: 0.88,
    torsoDepth: 0.87,
    belly: 0.06,
    chest: 0.13,
    legLength: 1.06,
    torsoLength: 0.97,
    legThickness: 0.86,
    neckWidth: 0.88,
    handScale: 1.04,
    headWidth: 0.92,
    headLength: 1.08,
    stoop: 0.025,
    hairline: 0.16,
    ageLines: 0.34,
    jawWidth: 0.88,
    noseLength: 1.16,
    noseWidth: 0.88,
  },
  face: {
    jawWidth: 0.88,
    chinWidth: 0.90,
    cheekbone: 1.13,
    cheekFullness: 0.20,
    foreheadSlope: 0.28,
    noseLength: 1.16,
    noseWidth: 0.88,
    noseBridge: 1.14,
    noseTip: 0.94,
    eyeSpacing: 0.96,
    eyeSize: 0.91,
    eyeTilt: -0.025,
    eyeDepth: 0.64,
    browWeight: 1.10,
    lidWeight: 0.37,
    mouthWidth: 0.98,
    lipFullness: 1.10,
    earSize: 1.04,
    age: 0.34,
    asymmetry: 0.045,
    freckles: 0.08,
    beardLength: 1.08,
    beardDensity: 1.16,
    moustacheShape: 'trimmed',
    hairPart: -0.35,
    hairWave: 0.18,
  },
  motion: {
    cadence: 1.06,
    stride: 1.07,
    hipSway: 0.78,
    shoulderSway: 1.07,
    forwardLean: 0.042,
    headSteadiness: 1.10,
    stanceWidth: 0.94,
    footLift: 1.04,
    idleBreath: 1.03,
    turnLag: 0.89,
    handEnergy: 1.06,
  },
  tailoring: {
    fabric: 'linen',
    weave: 0.83,
    roughness: 0.90,
    wear: 0.47,
    foldScale: 1.18,
    buttonMetal: 'horn',
    seamContrast: 0.86,
  },
  references: [
    {
      title: 'Self-Portrait as a Painter — Van Gogh Museum',
      url: 'https://www.vangoghmuseum.nl/en/collection/s0022V1962',
      date: 'December 1887–February 1888',
      observed: 'Near-period identity reference; the museum interpretation describes green eyes, a red beard, a frowning expression and a blue workman\'s smock.',
    },
    {
      title: 'A cheap model: Self-Portrait as a Painter — Van Gogh Museum',
      url: 'https://ontrafel.vangogh.nl/en/story/23/a-cheap-model/',
      date: '1887–1888',
      observed: 'Museum interpretation supports recessed, earnest eyes and the beard/smock colour contrast; the portrait expresses a particular moment rather than a permanent mood.',
    },
    {
      title: 'Self-Portrait as a Painter — Courtauld exhibition interpretation',
      url: 'https://virtualtour.courtauld.ac.uk/gal-hotspot/self-portrait-as-a-painter/',
      date: 'December 1887–February 1888',
      observed: 'Van Gogh\'s quoted description supports muted hair, fuller lips, restrained forehead and mouth lines, an unkempt red beard and coarse blue linen. The painting belongs to the Van Gogh Museum.',
    },
    {
      title: 'Self-Portrait with a Straw Hat — The Metropolitan Museum of Art',
      url: 'https://www.metmuseum.org/art/collection/search/436532',
      date: '1887',
      observed: 'Near-period straw-hat identity reference. The game exaggerates the worn brim and pairs it with a fictional apron costume.',
    },
  ],
};
