import {CHARACTER_DESIGNS} from './character-designs/index.js';
/** Historical artists; fictional crews, combat roles and visual art direction.
 * Ages are at 31 December 1888. Body proportions are not biographical measurements.
 * See docs/ART-WORLD.md and docs/CHARACTER-DESIGN.md for museum references.
 */
export const HISTORY_DISCLAIMER = '1880년대 예술가들에게서 영감을 받은 상상의 대립.';
export const FICTION_NOTE = '화가들은 실존 인물이며, 크루와 전투 역할, 의상, 라이벌 관계는 모두 상상입니다.';
export const ROLES = Object.freeze(['vanguard', 'flanker', 'anchor', 'marksman', 'support', 'scout']);
export const FACTIONS = [
  {
    "id": 0,
    "name": "노란 집",
    "shortName": "노란 집",
    "color": "#f1ca63",
    "darkColor": "#735321",
    "accent": "#fff0ae",
    "motto": "다른 비전을 위한 자리를 내어라.",
    "description": "반 고흐의 표현주의적 터치에서 쇠라의 측정된 점까지, 상상의 색 실험자 크루.",
    "style": "해바라기 황금, 넓은 색면, 대담한 실루엣.",
    "roster": [
      {
        "name": "Vincent van Gogh",
        "shortName": "Van Gogh",
        "age1888": 35,
        "role": "vanguard",
        "epithet": "The Sunflower",
        "artNote": "In 1888, Van Gogh prepared the Yellow House in Arles for a shared artists’ studio.",
        "sourceUrl": "https://www.vangoghmuseum.nl/en/collection/s0032V1962",
        "look": {
          "hat": "frayedstraw",
          "hair": "short",
          "hairColor": "#ae603d",
          "beard": "short",
          "skin": "#dfae88",
          "coat": "smock",
          "trim": "#f4d97a",
          "build": "slim",
          "accessory": "apron",
          "stature": 1,
          "shoulderWidth": 0.9,
          "waistWidth": 0.86,
          "legLength": 1.05,
          "torsoLength": 0.97,
          "headWidth": 0.91,
          "headLength": 1.05,
          "jawWidth": 0.86,
          "noseLength": 1.08,
          "hairline": 0.12,
          "ageLines": 0.35,
          "eyeColor": "#64785e",
          "hatColor": "#bc9d55",
          "hatBandColor": "#735837",
          "coatColor": "#526b63",
          "shirtColor": "#d7c49d",
          "pantsColor": "#514d42",
          "sleeves": "rolled",
          "neckwear": "none",
          "beardShape": "square"
        },
        "personality": {
          "aggression": 0.82,
          "discipline": 0.63,
          "teamwork": 0.76,
          "curiosity": 0.8
        }
      },
      {
        "name": "Paul Gauguin",
        "shortName": "Gauguin",
        "age1888": 40,
        "role": "flanker",
        "epithet": "The Colourist",
        "artNote": "Gauguin joined Van Gogh in Arles in October 1888; their ways of painting often differed.",
        "sourceUrl": "https://archive.artic.edu/vangogh/studiosud.html",
        "look": {
          "hat": "slouchberet",
          "hair": "long",
          "hairColor": "#38291f",
          "beard": "moustache",
          "skin": "#c9936d",
          "coat": "doublebreast",
          "trim": "#d69369",
          "build": "broad",
          "accessory": "none",
          "stature": 1.04,
          "shoulderWidth": 1.18,
          "waistWidth": 1.06,
          "legLength": 0.99,
          "torsoLength": 1.07,
          "headWidth": 1.1,
          "headLength": 1.04,
          "jawWidth": 1.13,
          "noseLength": 1.23,
          "noseWidth": 1.15,
          "hairline": 0.1,
          "ageLines": 0.42,
          "hatColor": "#6c4038",
          "coatColor": "#825344",
          "shirtColor": "#c6b89b",
          "pantsColor": "#3f4744",
          "sleeves": "cuffed",
          "neckwear": "kerchief"
        },
        "personality": {
          "aggression": 0.76,
          "discipline": 0.72,
          "teamwork": 0.61,
          "curiosity": 0.91
        }
      },
      {
        "name": "Paul Cézanne",
        "shortName": "Cézanne",
        "age1888": 49,
        "role": "anchor",
        "epithet": "The Mountain",
        "artNote": "Cézanne developed increasingly ordered brushwork during the 1880s, building form through colour.",
        "sourceUrl": "https://www.nationalgallery.org.uk/artists/paul-cezanne",
        "look": {
          "hat": "none",
          "hair": "bald",
          "hairColor": "#635044",
          "beard": "full",
          "skin": "#d9ad8b",
          "coat": "vest",
          "trim": "#bdb17d",
          "build": "broad",
          "accessory": "waistapron",
          "stature": 0.99,
          "shoulderWidth": 1.1,
          "waistWidth": 1.22,
          "legLength": 0.97,
          "torsoLength": 1.08,
          "headWidth": 1.12,
          "headLength": 0.98,
          "jawWidth": 1.13,
          "noseWidth": 1.13,
          "hairline": 0.88,
          "ageLines": 0.6,
          "stoop": 0.055,
          "coatColor": "#63584f",
          "shirtColor": "#d5c7ab",
          "pantsColor": "#62513f",
          "sleeves": "rolled",
          "neckwear": "none",
          "apronColor": "#bca976",
          "beardShape": "fan"
        },
        "personality": {
          "aggression": 0.46,
          "discipline": 0.88,
          "teamwork": 0.8,
          "curiosity": 0.55
        }
      },
      {
        "name": "Georges Seurat",
        "shortName": "Seurat",
        "age1888": 29,
        "role": "marksman",
        "epithet": "The Measured Light",
        "artNote": "Seurat first exhibited La Grande Jatte at the final Impressionist exhibition in 1886.",
        "sourceUrl": "https://archive.artic.edu/seurat/seurat_themes.html",
        "look": {
          "hat": "none",
          "hair": "short",
          "hairColor": "#332b27",
          "beard": "full",
          "skin": "#ddba9a",
          "coat": "frock",
          "trim": "#d7c7a3",
          "build": "slim",
          "accessory": "none",
          "stature": 1.08,
          "shoulderWidth": 0.92,
          "waistWidth": 0.88,
          "legLength": 1.12,
          "torsoLength": 0.98,
          "headWidth": 0.88,
          "headLength": 1.1,
          "jawWidth": 0.92,
          "noseLength": 1.1,
          "hairline": 0.04,
          "ageLines": 0.08,
          "coatColor": "#3c494a",
          "shirtColor": "#e4d9be",
          "pantsColor": "#3b413e",
          "sleeves": "fitted",
          "neckwear": "stock",
          "beardShape": "pointed"
        },
        "personality": {
          "aggression": 0.4,
          "discipline": 0.98,
          "teamwork": 0.73,
          "curiosity": 0.65
        }
      },
      {
        "name": "Paul Signac",
        "shortName": "Signac",
        "age1888": 25,
        "role": "support",
        "epithet": "The Harbour",
        "artNote": "Signac was a leading Neo-Impressionist and visited his friend Van Gogh in Arles in March 1889.",
        "sourceUrl": "https://vangoghletters.org/vg/letters/let752/letter.html",
        "look": {
          "hat": "sailor",
          "hair": "short",
          "hairColor": "#705039",
          "beard": "full",
          "skin": "#e0b591",
          "coat": "sailor",
          "trim": "#c7b76b",
          "build": "broad",
          "accessory": "none",
          "stature": 1.03,
          "shoulderWidth": 1.12,
          "waistWidth": 1.07,
          "legLength": 1.03,
          "torsoLength": 1.03,
          "headWidth": 1.04,
          "headLength": 0.96,
          "jawWidth": 1.05,
          "noseWidth": 1.05,
          "hairline": 0.03,
          "ageLines": 0.08,
          "hatColor": "#c6c8ae",
          "coatColor": "#304b55",
          "shirtColor": "#d5d6b9",
          "pantsColor": "#374448",
          "sleeves": "cuffed",
          "neckwear": "kerchief"
        },
        "personality": {
          "aggression": 0.38,
          "discipline": 0.83,
          "teamwork": 0.98,
          "curiosity": 0.56
        }
      },
      {
        "name": "Henri de Toulouse-Lautrec",
        "shortName": "Toulouse-Lautrec",
        "age1888": 24,
        "role": "scout",
        "epithet": "The Night Sketch",
        "artNote": "Toulouse-Lautrec became known for his depictions of performers and the life of Montmartre.",
        "sourceUrl": "https://www.musee-toulouse-lautrec.com/collections/henri-de-toulouse-lautrec/",
        "look": {
          "hat": "bowler",
          "hair": "curly",
          "hairColor": "#3f2c24",
          "beard": "short",
          "skin": "#d9ad8c",
          "coat": "frock",
          "trim": "#bd9767",
          "build": "broad",
          "accessory": "glasses",
          "stature": 0.844444,
          "shoulderWidth": 1.03,
          "waistWidth": 1.08,
          "legLength": 0.68,
          "torsoLength": 1.13,
          "headWidth": 1.08,
          "headLength": 1.02,
          "jawWidth": 1.04,
          "noseLength": 1.05,
          "noseWidth": 1.1,
          "hairline": 0.12,
          "ageLines": 0.13,
          "hatColor": "#393138",
          "hatBandColor": "#b89a63",
          "coatColor": "#634750",
          "shirtColor": "#d9c6a7",
          "pantsColor": "#443d42",
          "sleeves": "fitted",
          "neckwear": "bow",
          "beardShape": "square"
        },
        "personality": {
          "aggression": 0.64,
          "discipline": 0.73,
          "teamwork": 0.72,
          "curiosity": 0.98
        }
      }
    ],
    "facts": [
      {
        "title": "A studio imagined",
        "text": "Van Gogh hoped to build an artists’ community in the Yellow House. Gauguin was the only artist who lived and worked there with him. This expanded crew is fictional.",
        "url": "https://www.vangoghmuseum.nl/en/collection/s0032V1962"
      },
      {
        "title": "Friends across styles",
        "text": "Signac visited Van Gogh in Arles in March 1889. Their friendship crossed differences in painting technique.",
        "url": "https://vangoghletters.org/vg/letters/let752/letter.html"
      },
      {
        "title": "Colour and structure",
        "text": "Cézanne associated with the Impressionists while pursuing his own ordered approach to form and colour.",
        "url": "https://www.nationalgallery.org.uk/artists/paul-cezanne"
      }
    ]
  },
  {
    "id": 1,
    "name": "인디펜던츠",
    "shortName": "인디펜던츠",
    "color": "#70cbed",
    "darkColor": "#245568",
    "accent": "#c3edfb",
    "motto": "각자의 방식으로 빛을 잡아라.",
    "description": "현대적 삶을 각자의 방식으로 그리는 상상의 인상파 대표 크루.",
    "style": "코발트 블루, 빛나는 액센트, 그리고 개성 강한 실루엣.",
    "roster": [
      {
        "name": "Claude Monet",
        "shortName": "Monet",
        "age1888": 48,
        "role": "vanguard",
        "epithet": "The Changing Light",
        "artNote": "Monet settled at Giverny in 1883; he explored how changing light transformed a subject.",
        "sourceUrl": "https://www.nationalgallery.org.uk/artists/claude-monet",
        "look": {
          "hat": "garden",
          "hair": "short",
          "hairColor": "#79736a",
          "beard": "full",
          "skin": "#d5a681",
          "coat": "smock",
          "trim": "#a9c2bf",
          "build": "broad",
          "accessory": "none",
          "stature": 1.01,
          "shoulderWidth": 1.13,
          "waistWidth": 1.2,
          "legLength": 0.98,
          "torsoLength": 1.05,
          "headWidth": 1.14,
          "headLength": 1.01,
          "jawWidth": 1.13,
          "noseLength": 1.08,
          "noseWidth": 1.17,
          "hairline": 0.3,
          "ageLines": 0.57,
          "hatColor": "#797c59",
          "hatBandColor": "#a9bca8",
          "coatColor": "#617362",
          "shirtColor": "#bfc6b1",
          "pantsColor": "#4c5d55",
          "sleeves": "cuffed",
          "neckwear": "kerchief",
          "beardShape": "fan"
        },
        "personality": {
          "aggression": 0.84,
          "discipline": 0.66,
          "teamwork": 0.82,
          "curiosity": 0.71
        }
      },
      {
        "name": "Pierre-Auguste Renoir",
        "shortName": "Renoir",
        "age1888": 47,
        "role": "flanker",
        "epithet": "The Warm Light",
        "artNote": "Renoir and Monet painted together on the Seine in 1869, developing lighter colours and broken brushwork.",
        "sourceUrl": "https://www.nationalgallery.org.uk/artists/pierre-auguste-renoir",
        "look": {
          "hat": "none",
          "hair": "short",
          "hairColor": "#996543",
          "beard": "short",
          "skin": "#e1b595",
          "coat": "vest",
          "trim": "#a8c7e1",
          "build": "slim",
          "accessory": "none",
          "stature": 0.97,
          "shoulderWidth": 0.85,
          "waistWidth": 0.84,
          "legLength": 1.02,
          "torsoLength": 0.97,
          "headWidth": 0.89,
          "headLength": 1.02,
          "jawWidth": 0.85,
          "noseLength": 0.94,
          "noseWidth": 0.87,
          "hairline": 0.65,
          "ageLines": 0.48,
          "stoop": 0.03,
          "coatColor": "#875a53",
          "shirtColor": "#d4c7ab",
          "pantsColor": "#51484c",
          "sleeves": "rolled",
          "neckwear": "bow"
        },
        "personality": {
          "aggression": 0.73,
          "discipline": 0.78,
          "teamwork": 0.81,
          "curiosity": 0.89
        }
      },
      {
        "name": "Edgar Degas",
        "shortName": "Degas",
        "age1888": 54,
        "role": "anchor",
        "epithet": "The Gesture",
        "artNote": "Degas exhibited with the Impressionists and studied modern life through drawing, painting and pastel.",
        "sourceUrl": "https://www.nationalgallery.org.uk/artists/hilaire-germain-edgar-degas",
        "look": {
          "hat": "none",
          "hair": "bald",
          "hairColor": "#8b8274",
          "beard": "short",
          "skin": "#d9b493",
          "coat": "doublebreast",
          "trim": "#aebdd1",
          "build": "average",
          "accessory": "none",
          "stature": 1.025,
          "shoulderWidth": 1.01,
          "waistWidth": 1.03,
          "legLength": 1.04,
          "torsoLength": 1.01,
          "headWidth": 0.96,
          "headLength": 1.08,
          "jawWidth": 1.03,
          "noseLength": 1.18,
          "hairline": 0.79,
          "ageLines": 0.72,
          "stoop": 0.07,
          "coatColor": "#444951",
          "shirtColor": "#c2c6bd",
          "pantsColor": "#3b424c",
          "sleeves": "fitted",
          "neckwear": "cravat",
          "beardShape": "square"
        },
        "personality": {
          "aggression": 0.47,
          "discipline": 0.94,
          "teamwork": 0.79,
          "curiosity": 0.5
        }
      },
      {
        "name": "Berthe Morisot",
        "shortName": "Morisot",
        "age1888": 47,
        "role": "marksman",
        "epithet": "The Open Air",
        "artNote": "Morisot was a principal Impressionist, exhibiting alongside Monet, Renoir, Degas and Pissarro.",
        "sourceUrl": "https://www.marmottan.fr/collections/berthe-morisot/",
        "look": {
          "hat": "bonnet",
          "hair": "waved",
          "hairColor": "#aca39b",
          "beard": "none",
          "skin": "#e4bc9f",
          "coat": "highcollar",
          "trim": "#d6be8b",
          "build": "slim",
          "accessory": "shawl",
          "presentation": "woman",
          "stature": 0.975,
          "shoulderWidth": 0.82,
          "waistWidth": 0.88,
          "legLength": 1.03,
          "torsoLength": 0.99,
          "headWidth": 0.87,
          "headLength": 1.08,
          "jawWidth": 0.8,
          "noseLength": 1.05,
          "noseWidth": 0.83,
          "hairline": 0.12,
          "ageLines": 0.53,
          "hatColor": "#414654",
          "hatBandColor": "#aaa6b5",
          "coatColor": "#53657d",
          "shirtColor": "#c6c8bf",
          "pantsColor": "#444c61",
          "sleeves": "puff",
          "neckwear": "none"
        },
        "personality": {
          "aggression": 0.45,
          "discipline": 0.94,
          "teamwork": 0.65,
          "curiosity": 0.72
        }
      },
      {
        "name": "Camille Pissarro",
        "shortName": "Pissarro",
        "age1888": 58,
        "role": "support",
        "epithet": "The Orchard",
        "artNote": "Pissarro adopted Neo-Impressionism in 1886, then returned to freer brushwork by 1890.",
        "sourceUrl": "https://www.ashmolean.org/view-my-window",
        "look": {
          "hat": "floppy",
          "hair": "bald",
          "hairColor": "#d6d1c4",
          "beard": "full",
          "skin": "#d8ad8b",
          "coat": "smock",
          "trim": "#9fc6d0",
          "build": "slim",
          "accessory": "glasses",
          "stature": 0.985,
          "shoulderWidth": 0.95,
          "waistWidth": 1.02,
          "legLength": 1,
          "torsoLength": 1,
          "headWidth": 0.96,
          "headLength": 1.09,
          "jawWidth": 0.96,
          "noseLength": 1.2,
          "noseWidth": 1.05,
          "hairline": 0.92,
          "ageLines": 0.92,
          "stoop": 0.12,
          "hatColor": "#8d8978",
          "hatBandColor": "#6b766f",
          "coatColor": "#827257",
          "shirtColor": "#cad0c2",
          "pantsColor": "#566066",
          "sleeves": "cuffed",
          "neckwear": "kerchief",
          "beardShape": "flowing"
        },
        "personality": {
          "aggression": 0.37,
          "discipline": 0.85,
          "teamwork": 0.98,
          "curiosity": 0.68
        }
      },
      {
        "name": "Mary Cassatt",
        "shortName": "Cassatt",
        "age1888": 44,
        "role": "scout",
        "epithet": "The Modern Eye",
        "artNote": "Cassatt joined the Impressionist exhibitions in 1879, returning in 1880, 1881 and 1886.",
        "sourceUrl": "https://www.metmuseum.org/essays/mary-stevenson-cassatt-1844-1926",
        "look": {
          "hat": "portrait",
          "hair": "pinned",
          "hairColor": "#745344",
          "beard": "none",
          "skin": "#e2b392",
          "coat": "cape",
          "trim": "#d5a29b",
          "build": "average",
          "accessory": "capelet",
          "presentation": "woman",
          "stature": 1.015,
          "shoulderWidth": 1.02,
          "waistWidth": 1.08,
          "legLength": 1.01,
          "torsoLength": 1.05,
          "headWidth": 1.07,
          "headLength": 0.98,
          "jawWidth": 0.99,
          "noseLength": 0.97,
          "noseWidth": 1.02,
          "hairline": 0.08,
          "ageLines": 0.43,
          "hatColor": "#6e526a",
          "hatBandColor": "#abc4d1",
          "coatColor": "#675c7a",
          "shirtColor": "#d7cebf",
          "pantsColor": "#4b4b62",
          "sleeves": "puff",
          "neckwear": "none"
        },
        "personality": {
          "aggression": 0.58,
          "discipline": 0.83,
          "teamwork": 0.73,
          "curiosity": 0.97
        }
      }
    ],
    "facts": [
      {
        "title": "Independent visions",
        "text": "These painters participated in the Impressionist movement. The game’s crew name does not claim membership of the Société des artistes indépendants.",
        "url": "https://www.nationalgallery.org.uk/artists/hilaire-germain-edgar-degas"
      },
      {
        "title": "Morisot’s place",
        "text": "Morisot was a principal member of the Impressionist group, alongside Monet, Renoir, Degas and Pissarro.",
        "url": "https://www.marmottan.fr/collections/berthe-morisot/"
      },
      {
        "title": "Cassatt’s exhibitions",
        "text": "Invited by Degas, Cassatt exhibited with the Impressionists in 1879, 1880, 1881 and 1886.",
        "url": "https://www.metmuseum.org/essays/mary-stevenson-cassatt-1844-1926"
      },
      {
        "title": "Changing methods",
        "text": "Pissarro tried Neo-Impressionism from 1886 before returning to freer brushwork by 1890.",
        "url": "https://www.ashmolean.org/view-my-window"
      }
    ]
  }
];
export const FACTION_BY_ID = Object.fromEntries(FACTIONS.map(faction => [faction.id, faction]));

// The same authored identity drives the mesh, animation and close-up portraits.
for(const faction of FACTIONS)for(const artist of faction.roster){
 const design=CHARACTER_DESIGNS[artist.shortName];
 artist.design=design;
 artist.look={...artist.look,...design.look,characterId:design.id,age1888:artist.age1888,face:{...design.face},motion:{...design.motion},tailoring:{...design.tailoring}};
}
